module.exports = {
    MONGO_URI:process.env.MONGO_URI,
    JWT_SECRET:process.env.JWT_SECRET,
    BRAINTREE_MERCHANT_ID:process.env.BRAINTREE_MERCHANT_ID,
    BRAINTREE_PUBLIC_KEY:process.env.BRAINTREE_PUBLIC_KEY,
    BRAINTREE_PRIVATE_KEY:process.env.BRAINTREE_PRIVATE_KEY 
}